### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by 1337god** [cquest/tootbot#10]
All the account information is correct but it just gives me "ERROR: First Login Failed!" every time, I even changed the password a couple of times already.

**Comment by 1337god** [comment]
Tried switching from email to actual mastodon address but none work. I'm using https://botsin.space/

**Comment by singlespeedfahrer** [comment]
Had the same problem but could solve it with a change in tootbot.py:
(begins in line 82)
>                 mastodon_api.log_in(
>                     #username=mastodon,
>                     'MyLoginMail@Adress',
>                     [...]

Perhaps it was a change in the Mastodon module? Haven't figured out it yet.

**Comment by Dinth** [comment]
Thanks, the above worked for me.
But also it looks like the passwords are mishandled, even if they are inside of quotes. Having a complex password with lots of special characters completely breaks the script

**Comment by hmlendea** [comment]
@singlespeedfahrer's solution works... but:
Another thing to make sure is to have the email address in all lowercase letters. If there's any uppercase character, it will result in the dreaded `ERROR: First Login Failed!` error

**Comment by myusuf3** [comment]
I am still getting this error even after we moved to using secret.  any ideas? looks like secret has a newline in it.

**Comment by myusuf3** [comment]
Seems like its failing on login in step specifically.
