### ISSUE TITLE
urllib3 existing

### ISSUE THREAD

**Issue by osauzet** [cquest/tootbot#19]
Hi, is it possible to install your bot on an mastodon instance ?
I have this error on my server : 

Found existing installation: urllib3 1.24.1
    Not uninstalling urllib3 at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'urllib3'. No files were found to uninstall.

And when i try to run the bot : 
/usr/lib/python3/dist-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.13) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)

Thanks for your help...
Olivier.S

**Comment by cquest** [comment]
Package version numbers have been added to make sure pip installs the right/tested ones

https://github.com/cquest/tootbot/commit/46be184d410e4595d550fdd2c9a898bf61418a99
